# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [1]:
jupyter notebook --browser='C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s'C:\ProgramData\Microsoft\Windows\Start Menu\Programs

SyntaxError: invalid syntax (3699362617.py, line 1)

In [2]:
import numpy as np
import pandas as pd

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [3]:

arr=np.random.rand(4,7)*20
arr


array([[ 6.55823399,  0.86802717, 18.07311209,  2.71014822,  0.97730908,
         2.34988337,  3.74219711],
       [11.96925491, 14.96143   ,  7.37760362,  0.12963659, 11.57533306,
        14.53967401, 15.49868953],
       [17.1748237 ,  3.65419308,  5.74628247,  8.14411885,  0.06093059,
         2.55526962,  2.40704351],
       [11.39551795, 15.90191759, 18.31018735, 10.81811085,  5.83562456,
        13.18770217,  9.0410953 ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [4]:
a=np.random.rand(8,10)*10
b=np.sum(a,axis=1)
print(b)
print(np.where(b==min(b)))

[63.73323401 21.98335187 59.5528911  54.34349778 42.26727532 50.30191981
 75.95150053 48.62461379]
(array([1], dtype=int64),)


In [5]:
s='8.63630107 6.59171319 7.20748295 5.15759821 4.46956498 7.6494641 0.1930845 7.83360852 8.47987613 4.16339688'
s1=s.split(' ')
print(s1)
s2=list(map(float,s1))
print(sum(s2))

['8.63630107', '6.59171319', '7.20748295', '5.15759821', '4.46956498', '7.6494641', '0.1930845', '7.83360852', '8.47987613', '4.16339688']
60.38209053


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [6]:
x=np.arange(0,18,2)
y=np.arange(1,10,1)
c=(np.sum((x-y)**2))**0.5
c

11.874342087037917

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.


In [7]:
A =np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B=np.array([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])
np.linalg.inv(B),np.linalg.inv(A)
x=np.linalg.inv(A)@(C*(-1))@np.linalg.inv(B)
x

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [8]:
import csv
with open('minutes_n_ingredients.csv') as f:
    f1=csv.reader(f,delimiter=',')
    heading=next(f1)
    file=np.loadtxt('minutes_n_ingredients.csv', delimiter=',',dtype='int32',skiprows=1)
heading,file[:5]
file

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [9]:
s=file[:,1:].sum(axis=0)
average_sum=s/file.shape[0]
mini=np.min(file[:,1:],0)
maxi=np.max(file[:,1:],0)
median=np.median(file[:,1:],0)
median

array([40.,  9.])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [10]:
import numpy as np
np.quantile(file[:,1], 0.5)

40.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [11]:
k=file[file[:,1]==0]
file1=file.copy()
file1[file1==0]=1
file1
np.savetxt("file1.csv", file1, delimiter=",")

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [12]:
new=np.unique(file[:,1:])
new.shape[0]


656

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [13]:
new=np.unique(file[:,2])
new,new.shape[0]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39]),
 37)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [14]:
new_file=file[file[:,2]<=5]
new_file,new_file.shape[0]

(array([[446597,     15,      5],
        [204134,      5,      3],
        [ 25623,      6,      4],
        ...,
        [ 52088,     60,      5],
        [128811,     15,      4],
        [370915,      5,      4]]),
 17262)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [15]:
n=np.array(file[:,2]/file[:,1],dtype='int')
np.max(n)

C:\Users\maria\AppData\Local\Temp\ipykernel_16432\1532786431.py:1: RuntimeWarning: divide by zero encountered in true_divide
  n=np.array(file[:,2]/file[:,1],dtype='int')


23

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [16]:
t=np.sort(file1, axis=-2).copy()
np.sum(t[-100:,1],dtype='int64')/100

21518445.39

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [17]:
s=np.random.rand(10)*file1.shape[0]
s=np.array(s,dtype=int)
print(s)
new=file1[s,:]
new

[49054  8930 20480 70822 39201 98330 66785 91929 71255 92351]


array([[303860,     55,      9],
       [116806,     20,     14],
       [154041,     15,      8],
       [499357,     35,      9],
       [ 21241,     25,      7],
       [157832,      8,      5],
       [ 19838,     35,      8],
       [381525,     30,      9],
       [  1975,      1,      3],
       [470485,     20,      9]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [18]:
average=np.sum(file1[:,-1])/file1.shape[0]
average
s=file1[file1[:,-1]<average]
str(s.shape[0]/file1.shape[0]*100)+' %'

'58.802 %'

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [19]:
n=pd.DataFrame(file1,columns=heading)
n['простой?'] = np.where((n['minutes'] <=20) & (n['n_ingredients'] <=5), 1, 0)

n=n.to_numpy()
n

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [23]:
s=file1[(file1[:,-1] <=20) & (file1[:,1] <=5)]
print(f'{s.shape[0]/file1.shape[0]*100} %')

6.333 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [28]:
# new=pd.DataFrame(file1,columns=heading)
# # conditions = [(new['minutes'] <10), (10<=new['minutes']<20), (new['minutes']>=20)]
# # choices = [1, 2, 3] #1- короткий рецепт, 2 - стандартный, 3 - длинный
# # new['группа'] = np.select(conditions, choices)
# new['группа'] = [1 if x <10 elif 10<=x<20 else  for x in df['Set']]
file1

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

In [228]:
df = pd.DataFrame(file1,columns=heading)
# print(df)
conditions = [(df['minutes'] <10), (df['minutes'] >=10) & (df['minutes'] <20), (df['minutes'] >=20)]
choices = [1, 2, 3]#1- короткий рецепт, 2 - стандартный, 3 - длинный
df['group'] = np.select(conditions, choices)

n1_1=df[df['group']==1]
n1_2=df[df['group']==2]
n1_3=df[df['group']==3]

num=int((min((n1_1.shape[0],n1_2.shape[0],n1_3.shape[0])))**(1/3))
gr1=n1_1[:3]['group'].to_numpy()
gr2=n1_2[:3]['group'].to_numpy()
gr3=n1_3[:3]['group'].to_numpy()
r1=n1_1['id'][:3]
r2=n1_2['id'][:3]
r3=n1_3['id'][:3]

inf_1=n1_1[['n_ingredients']][:3].to_numpy()

inf_2=n1_2[['n_ingredients']][:3].to_numpy()
inf_3=n1_3[['n_ingredients']][:3].to_numpy()
d1=np.concatenate((gr1,gr2,gr3),axis=None)
d2=np.concatenate((r1,r2,r3),axis=None)
d3=np.concatenate((inf_1,inf_2,inf_3),axis=None)
d=np.concatenate((d1,d2,d3),axis=None)
d.reshape(3,3,3)
# n2=df['id'].to_numpy()
# n3=df.iloc[:,[1,2]].to_numpy()n1_1[:num]


array([[[     1,      1,      1],
        [     2,      2,      2],
        [     3,      3,      3]],

       [[ 67660, 366174, 204134],
        [ 94746,  33941, 446597],
        [127244,  23891, 157911]],

       [[     6,      9,      3],
        [     6,      9,      5],
        [    16,      7,     14]]])